### ISSUE TITLE
Version 5.0 error in template submit-close.ftl

### ISSUE THREAD

**Issue by afattahi54** [struts-community-plugins/struts2-jquery#304]
Thanks for new version :)

After upgrade to version 5.0.0, I face this error:

````
FreeMarker template error:
Template inclusion failed (for parameter value "/template/simple/submit-close.ftl"):
Syntax error in template "template/simple/submit-close.ftl" in line 22, column 95:
?no_esc can't be used here, as the current output format isn't a markup (escaping) format: undefined(mimeType=null, class=f.c.UndefinedOutputFormat)

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #include "/${parameters.templateDir}/...  [in template "template/jquery/submit-close.ftl" at line 22, column 3]
----

Java stack trace (for programmers):
----
freemarker.core._MiscTemplateException: [... Exception message was already printed; see it above ...]
	at freemarker.core.Include.accept(Include.java:164)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at freemarker.template.Template.process(Template.java:383)
	at org.apache.struts2.components.template.FreemarkerTemplateEngine.renderTemplate(FreemarkerTemplateEngine.java:154)
	at org.apache.struts2.components.UIBean.mergeTemplate(UIBean.java:588)
	at com.jgeppert.struts2.jquery.components.Submit.end(Submit.java:255)
	at org.apache.struts2.views.jsp.ComponentTagSupport.doEndTag(ComponentTagSupport.java:40)
````

**Comment by jogep** [comment]
@afattahi54 are you using Struts2 version 6.0.0 as the simple theme is provided by Struts itself.

**Comment by afattahi54** [comment]
Yes I have not set/change any struts defaults about theme

**Comment by sdutry** [comment]
There was 1 PR merged with a ?no_esc instead of the Javascript escape tags
in the ftl file, needs to be changed tot fix it

Op za 27 aug. 2022 15:12 schreef afattahi54 ***@***.***>:

**Comment by sdutry** [comment]
@afattahi54 do you have your own versions of Freemarker defined, or do you have custom settings for Freemarker defined.
(it's complaining about not having a default markup (escaping) format as output format)

Can you provide a (minimal) project setup to reproduce the issue?

**Comment by afattahi54** [comment]
@sdutry the below was set in freemaker.properties.

````
output_format=undefined
````

I removed and now it works.

Thanks!
